name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -tmilankacha/testing
      - name: Push Docker Image
        run: docker push -t milankacha/testing:latest

    deploy:
        need: build
        runs-on: aws-ec2
        steps:
        - name: Pull image from docker hub
        - run: docker pull milankacha/testing:latest
        - name: Delete old container
        - run: docker rm -f reactContainer || true
        - name: Run Docker Container
        - run:  docker run -d -p 5173:80 --name your-container milankacha/testing:latest

        
